POST http://localhost:4000/login
Content-Type: application/json

{
    "email" : "abdullahozair@gmail.com",
    "password":"123"
}

####

POST http://localhost:4000/register
Content-Type: application/json

{
    "name" : "abdullah",
    "email" : "abdullahozair0@gmail.com",
    "password":"123"
}

###
POST http://localhost:4000/forgotpassword
Content-Type: application/json

{
    "email" : "abdullahozair000@gmail.com",
}